# yaml-language-server: $schema=https://raw.githubusercontent.com/streetsidesoftware/cspell/main/packages/cspell-tools/cspell-tools.config.schema.json

targets:
  - name: "z3-solver"
    sources:
      - "src/z3-solver.txt"
    format: "plaintext"
    targetDirectory: "./dict"
    generateNonStrict: false
    compress: false
